# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b5661b4c577cf53bcd807599c460a1d79eff3a11bba0dfa3e214eee8b93de07359f903fe9fbdaeeda4e03e6afaa724b22466b06345d9a5409e3eee3c0b59f49

test:
  secret_key_base: 245ce0eaf99706e9f3f35debee22b94c726a50d155c76d17273aa5d67b76ace9158f49bf54208661549aa6748fb1d79ea1d3863212114c345dbcc266ea93bf17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
